services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000" # MinIO S3 API port
      - "9001:9001" # MinIO Console/UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data # Persist data to a local directory
    command: server /data --console-address ":9001"

  temporal:
    image: temporalio/temporal:latest
    command: ["server", "start-dev", "--ip", "0.0.0.0"]
    ports:
      - "7233:7233" # Main Temporal service port
      - "8233:8233" # Temporal UI

  pgvector:
    image: ankane/pgvector:latest
    hostname: pgvector
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
      - ./infra/pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgvector_data:
  minio_data:

networks:
  app_network:
    driver: bridge
