services:
  pgvector:
    image: ankane/pgvector:latest
    hostname: pgvector
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
    volumes:
      - ./infra/pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgvector_data:

networks:
  app_network:
    driver: bridge
