[project]
name = "gdai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "asyncpg>=0.30.0",
    "click>=8.1.8",
    "cohere>=5.15.0",
    "dramatiq[rabbitmq,watch]>=1.17.1",
    "fastapi-cli>=0.0.7",
    "fastapi[standard]>=0.115.12",
    "langchain[openai]>=0.3.25",
    "langgraph>=0.4.7",
    "mkdocs>=1.6.1",
    "mkdocs-dracula-theme>=1.0.7",
    "pgvector>=0.4.1",
    "pre-commit>=4.2.0",
    "pymupdf>=1.26.3",
    "python-dotenv>=1.1.0",
    "rich>=13.9.4",
    "scipy>=1.15.2",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.44.0",
    "taskipy>=1.14.1",
    "types-aiofiles>=24.1.0.20250606",
]


[dependency-groups]
test = ["pytest>=8.4.0", "pytest-cov>=6.2.1", "pre-commit>=4.2.0", "pytest-asyncio>=0.26.0"]


[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "UP", "I", "ARG"]
ignore = ["E203", "D203", "D213", "D212", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "ERA001"]

[tool.ruff.lint.pydocstyle]
convention = "google" # Use Google style to docstrings


[tool.pytest.ini_options]
filterwarnings = [
    "ignore::pydantic.warnings.PydanticDeprecatedSince20",
    "ignore:.*swigvarlink has no __module__ attribute:DeprecationWarning:importlib._bootstrap",
    "ignore:.*SwigPyObject has no __module__ attribute:DeprecationWarning:importlib._bootstrap",
    "ignore:.*SwigPyPacked has no __module__ attribute:DeprecationWarning:importlib._bootstrap",
    "ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning:sys",
]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"


[tool.taskipy.tasks]
configure-dev = { cmd = "uv sync --all-groups & pre-commit install & pre-commit install --hook-type pre-push", help = "Configure the environment" }
run-background-tasks = { cmd = "set -a;. ./.env; set +a;   uv run dramatiq src.background_tasks.extract_document src.background_tasks.embedding --process $DRAMATIQ_NUM_PROCESSES --threads $DRAMATIQ_NUM_THREADS_PER_PROCESS", help = "Run the background tasks with Dramatiq workers" }
run-api = { cmd = "uv run python -m src.api.main", help = "Run the FastAPI application" }
run-dev = { cmd = "task run-background-tasks  & task run-api", help = "Run the development server with Dramatiq workers and API" }
tests = { cmd = "pytest", help = "Run all unit tests" }
