name: Deploy to Server

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_documentation:
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install UV
        run: wget -qO- https://astral.sh/uv/install.sh | sh
      - name: Install required packages
        run: uv sync --all-groups
      - name: Copy ROADMAP files to docs directory
        run: cp ROADMAP.md docs/
      - name: Copy CHANGELOG files to docs directory
        run: cp CHANGELOG.md docs/
      - name: Copy README files to docs directory
        run: cp README.md docs/index.md
      - name: Build MkDocs site
        run: mkdocs gh-deploy --force
      - run: echo "Deployment to GitHub Pages completed successfully."
